"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import tuplelistresult as components_tuplelistresult
from typing import Optional


@dataclasses.dataclass
class DetectNerWrapperTextDetectNerNerTagsPostRequest:
    UNSET='__SPEAKEASY_UNSET__'
    ner_tags: Optional[str] = dataclasses.field(metadata={'path_param': { 'field_name': 'ner_tags', 'style': 'simple', 'explode': False }})
    request_body: str = dataclasses.field(metadata={'request': { 'media_type': 'text/plain' }})
    api_key: Optional[str] = dataclasses.field(default=UNSET, metadata={'header': { 'field_name': 'api-key', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class DetectNerWrapperTextDetectNerNerTagsPostResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    tuple_list_result: Optional[components_tuplelistresult.TupleListResult] = dataclasses.field(default=None)
    r"""Successful Response"""
    

