"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import optionallistresult as components_optionallistresult
from typing import Optional


@dataclasses.dataclass
class TextIdiomsWrapperTextIdiomsPostResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    optional_list_result: Optional[components_optionallistresult.OptionalListResult] = dataclasses.field(default=None)
    r"""Successful Response"""
    

