"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import textresult as components_textresult
from enum import Enum
from typing import Optional

class Mode(str, Enum):
    UPPERCASE = 'uppercase'
    LOWERCASE = 'lowercase'


@dataclasses.dataclass
class TextNormalizeWrapperTextNormalizePostRequest:
    UNSET='__SPEAKEASY_UNSET__'
    request_body: str = dataclasses.field(metadata={'request': { 'media_type': 'text/plain' }})
    mode: Optional[Mode] = dataclasses.field(default=Mode.UPPERCASE, metadata={'query_param': { 'field_name': 'mode', 'style': 'form', 'explode': True }})
    api_key: Optional[str] = dataclasses.field(default=UNSET, metadata={'header': { 'field_name': 'api-key', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class TextNormalizeWrapperTextNormalizePostResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    text_result: Optional[components_textresult.TextResult] = dataclasses.field(default=None)
    r"""Successful Response"""
    

