"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import strlistresult as components_strlistresult
from typing import Optional


@dataclasses.dataclass
class TextTokenizeWrapperTextTokenizePostRequest:
    UNSET='__SPEAKEASY_UNSET__'
    request_body: str = dataclasses.field(metadata={'request': { 'media_type': 'text/plain' }})
    break_point: Optional[str] = dataclasses.field(default=' ', metadata={'query_param': { 'field_name': 'break_point', 'style': 'form', 'explode': True }})
    api_key: Optional[str] = dataclasses.field(default=UNSET, metadata={'header': { 'field_name': 'api-key', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class TextTokenizeWrapperTextTokenizePostResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    str_list_result: Optional[components_strlistresult.StrListResult] = dataclasses.field(default=None)
    r"""Successful Response"""
    

