"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import textresult as components_textresult
from typing import Optional


@dataclasses.dataclass
class TextTranslateWrapperTextTranslateTargetLangPostRequest:
    UNSET='__SPEAKEASY_UNSET__'
    target_lang: str = dataclasses.field(metadata={'path_param': { 'field_name': 'target_lang', 'style': 'simple', 'explode': False }})
    request_body: str = dataclasses.field(metadata={'request': { 'media_type': 'text/plain' }})
    api_key: Optional[str] = dataclasses.field(default=UNSET, metadata={'header': { 'field_name': 'api-key', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class TextTranslateWrapperTextTranslateTargetLangPostResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    text_result: Optional[components_textresult.TextResult] = dataclasses.field(default=None)
    r"""Successful Response"""
    

