"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import tfidfoutputtype as components_tfidfoutputtype
from ...models.components import tupleresult as components_tupleresult
from typing import List, Optional


@dataclasses.dataclass
class TextTfidfWrapperTextTfidfPostRequest:
    UNSET='__SPEAKEASY_UNSET__'
    ngram_size: int = dataclasses.field(metadata={'query_param': { 'field_name': 'ngram_size', 'style': 'form', 'explode': True }})
    output_type: components_tfidfoutputtype.TFIDFOutputType = dataclasses.field(metadata={'query_param': { 'field_name': 'output_type', 'style': 'form', 'explode': True }})
    request_body: List[str] = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    api_key: Optional[str] = dataclasses.field(default=UNSET, metadata={'header': { 'field_name': 'api-key', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class TextTfidfWrapperTextTfidfPostResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    tuple_result: Optional[components_tupleresult.TupleResult] = dataclasses.field(default=None)
    r"""Successful Response"""
    

