"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ToxicInputType(str, Enum):
    PROFANITY = 'profanity'
    BIAS = 'bias'
    SARCASM = 'sarcasm'
