"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from blinguasdk import utils
from dataclasses_json import Undefined, dataclass_json
from typing import Any, List


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class TupleResult:
    results: List[Any] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('results') }})
    

